services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-matcher-api
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - mysql_db
      - mongo_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev

  # MySQL Database
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  # MongoDB Database
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
